### ISSUE TITLE
run ./configure error

### ISSUE THREAD

**Issue by bestpredicts** [helios-base/librcsc#1]
```bash
bash: ./configure

 No such file or directory

```

**Comment by hidehisaakiyama** [comment]
You need to run ./bootstrap (or autoreconf -i -f) for generating the configure script. This is the usual process of Autotools.

**Comment by bestpredicts** [comment]
> You need to run ./bootstrap (or autoreconf -i -f) for generating the configure script. This is the usual process of Autotools.

thank you
