### ISSUE TITLE
obsolete InterceptInfo 

### ISSUE THREAD

**Issue by CarlosEngler** [helios-base/librcsc#65]
Hey, the class InterceptInfo is called in "intercept_table", but its now an obsolete class.
Other than that, the current body_intercept is still the obsolete body_intercept.2009

**Comment by hidehisaakiyama** [comment]
I guess you have not updated your own team's code. If you like to update librcsc, you need to follow the changes. The latest helios-base supports the latest librcsc. Please refer to that code. If you cannot update your team's code, please use the previous versions of librcsc.
